/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#e6c184",
        "inverse-surface": "#392e27",
        "surface": "#fff8f5",
        "outline-variant": "#d1c5b5",
        "surface-variant": "#f2dfd3",
        "on-secondary-fixed": "#171e12",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c1c9b8",
        "tertiary": "#685c57",
        "tertiary-container": "#b7a8a2",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#483d39",
        "outline": "#7f7668",
        "on-tertiary-fixed": "#221a16",
        "inverse-on-surface": "#ffede3",
        "on-error": "#ffffff",
        "on-background": "#231a13",
        "primary": "#765a26",
        "on-primary-fixed": "#271900",
        "on-primary": "#ffffff",
        "surface-container-high": "#f8e5d9",
        "on-surface": "#231a13",
        "on-secondary-container": "#5d6556",
        "on-primary-container": "#533b09",
        "inverse-primary": "#e6c184",
        "secondary-container": "#dae2d0",
        "on-secondary-fixed-variant": "#41493c",
        "surface-container": "#feeadf",
        "on-tertiary-fixed-variant": "#504440",
        "background": "#fff8f5",
        "surface-bright": "#fff8f5",
        "on-error-container": "#93000a",
        "surface-container-highest": "#f2dfd3",
        "surface-dim": "#e9d6cb",
        "primary-fixed": "#ffdea9",
        "secondary-fixed": "#dde5d3",
        "surface-tint": "#765a26",
        "on-surface-variant": "#4e463a",
        "secondary": "#596152",
        "surface-container-low": "#fff1e9",
        "on-secondary": "#ffffff",
        "primary-container": "#c9a66b",
        "tertiary-fixed-dim": "#d3c3bd",
        "tertiary-fixed": "#f0dfd9",
        "on-primary-fixed-variant": "#5c4211",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "3.5rem",
        "space-xs": "0.375rem",
        margin: "1.25rem",
        "gutter-desktop": "2.5rem",
        "space-md": "1.25rem",
        "space-lg": "2rem",
        "space-sm": "0.75rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "5rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "display-xl-mobile": ["EB Garamond", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "title-md": ["Manrope", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "display-xl": ["EB Garamond", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-xl-mobile": ["38px", { lineHeight: "46px", letterSpacing: "0.03em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.015em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "0.03em", fontWeight: "400" }],
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "0.04em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
